/**
 * Devin hook config for pane status.
 *
 * Chorus injected Claude Code's status hooks with `claude --settings <path>`,
 * where the settings file was ADDITIVE. Devin's nearest equivalent, `--config
 * <path>`, is not: it REPLACES the user config at ~/.config/devin/config.json.
 * Pointing it at a hooks-only file would silently strip the user's org_id,
 * default model and permission allowlist — the pane would launch unauthenticated.
 *
 * So the per-pane config is the user's own config with our hooks merged in, and
 * the merge is careful: if the user already defines hooks for an event, ours are
 * APPENDED to theirs rather than replacing them.
 *
 * Events chosen (Devin's set is a superset of Claude Code's):
 *   SessionStart      -> report Devin's chosen session id (closes the --session-id gap)
 *   UserPromptSubmit  -> running
 *   Stop              -> idle
 *   PermissionRequest -> waiting   (the badge the user actually acts on)
 *   PostToolUse       -> running   (return to running once a grant is answered)
 *   SessionEnd        -> exited
 */

export interface HookCommand {
  type: 'command';
  command: string;
  timeout?: number;
}
export interface HookMatcher {
  matcher: string;
  hooks: HookCommand[];
}
export type HooksConfig = Record<string, HookMatcher[]>;

/** Events we bind, and the argument our hook script receives for each. */
export const HOOK_EVENTS: { event: string; arg: string }[] = [
  { event: 'SessionStart', arg: 'session' },
  { event: 'UserPromptSubmit', arg: 'running' },
  { event: 'Stop', arg: 'idle' },
  { event: 'PermissionRequest', arg: 'waiting' },
  { event: 'PostToolUse', arg: 'running' },
  { event: 'SessionEnd', arg: 'exited' },
];

/**
 * Build the hooks block. `scriptPath` is our OSC emitter; it is invoked with the
 * signal name and reads the hook payload (which always carries `session_id`) on
 * stdin.
 *
 * The timeout is deliberately small: a hook sits on the agent's critical path,
 * and this one only writes a few bytes to /dev/tty. If it ever hangs, we would
 * rather lose a status update than stall the agent.
 */
export function devinStatusHooks(scriptPath: string): HooksConfig {
  const config: HooksConfig = {};
  for (const { event, arg } of HOOK_EVENTS) {
    config[event] = [
      {
        matcher: '',
        hooks: [{ type: 'command', command: `node ${JSON.stringify(scriptPath)} ${arg}`, timeout: 5 }],
      },
    ];
  }
  return config;
}

/** Shallow-object guard — anything else means "the user config is unusable". */
function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/**
 * The user's config with our hooks merged in, non-destructively.
 *
 * A corrupt or unreadable user config degrades to "our hooks only" rather than
 * throwing: a pane with no auth config fails loudly at the Devin prompt, which
 * is a better failure than a pane that never launches.
 */
export function composeSessionConfig(userConfig: unknown, hooks: HooksConfig): Record<string, unknown> {
  const base: Record<string, unknown> = isRecord(userConfig) ? { ...userConfig } : {};
  const existing = isRecord(base.hooks) ? (base.hooks as HooksConfig) : {};

  const merged: HooksConfig = { ...existing };
  for (const [event, matchers] of Object.entries(hooks)) {
    const prior = Array.isArray(existing[event]) ? existing[event] : [];
    // Ours go last so a user hook that blocks an action still runs first.
    merged[event] = [...prior, ...matchers];
  }

  base.hooks = merged;
  return base;
}

/**
 * Source of the Node script the hooks invoke. Written once per profile.
 *
 * It writes to /dev/tty rather than stdout: hook stdout is parsed by Devin as
 * structured hook output (a JSON object can inject context or block a tool), so
 * emitting escapes there would at best be swallowed and at worst be misread.
 * /dev/tty is the pane's PTY because the hook is a descendant of the `devin`
 * process we spawned into that PTY.
 */
export function hookScriptSource(): string {
  return `#!/usr/bin/env node
// Generated by devin-agent-tmux. Emits OSC-777 to the pane's PTY.
// Usage: node hook.mjs <session|running|idle|waiting|exited>
import { openSync, writeSync, closeSync } from 'node:fs';

const signal = process.argv[2];
let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  let seq;
  if (signal === 'session') {
    let id;
    try { id = JSON.parse(raw).session_id; } catch { /* unparseable payload */ }
    // Nothing to report without an id — stay silent rather than emit a malformed
    // sequence the scanner would have to reject.
    if (!id) return done();
    seq = '\\x1b]777;pane;session;' + id + '\\x07';
  } else {
    seq = '\\x1b]777;pane;status;' + signal + '\\x07';
  }
  try {
    const fd = openSync('/dev/tty', 'w');
    writeSync(fd, seq);
    closeSync(fd);
  } catch { /* no controlling terminal (headless run) — status simply won't update */ }
  done();
});
// Never block the agent: exit 0 no matter what happened above.
function done() { process.exit(0); }
`;
}
